spring.application.name=event_manager
spring.datasource.url=jdbc:mysql://localhost:3306/event_management
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

server.port=8081

jwt.secret=z+rF3WDzyhimrraI3OH7EJBsqGHjIoqJ1AjQvUfaRQRFVcW+EPK6DZb886gTghcb
